### ISSUE TITLE
chore: config.toml performance adjustments

### ISSUE THREAD

**Issue by carloscip** [Sensei-Node/sei-network#5]
protocol: sei

We were told in discord to make this adjustments:
```
Hello folks, we have been looking at mempool configs and want to keep them updated given our chain is much faster than the defaults they were set for. Could you all please reduce to  `ttl-duration = "15s"` and `ttl-num-blocks = 30` ? (If you already have them set lower thats fine).

Additionally, just for validator nodes, it is safer to turn off the transaction indexer since it may have issues indexing large size transactions and cause memory issues. Please turn off the indexer by `setting indexer = ["null"]`
```

## Tasks
- [ ] Set `ttl-duration = "15s"` in config.toml
- [ ] Set `ttl-num-blocks = 30` in config.toml
- [ ] For validators set `setting indexer = ["null"]` in config.toml
